### ISSUE TITLE
Is this compatible with hostlists dns block?

### ISSUE THREAD

**Issue by Zankaria** [j4lc/ublock-filters#1]
### URL of the website

yes.com

### Reason

Cannot open a normal issue so I used the site removal one, but I wanted to ask if there is a list provided for blocking these websites at the `hosts` file level

**Comment by j4lc** [comment]
As the title of the repo suggest, those filters are made for [uBlock Origin](https://github.com/gorhill/uBlock).

hosts file blocking isn't, and won't be supported.
